options(encoding = "UTF-8")

# ---- packages ----
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
library(fresh)
library(shinyjs)
library(rhandsontable)
library(rmarkdown)
library(pdftools)
library(knitr)
library(kableExtra)
library(digest)
library(DBI)
library(RPostgres)
library(jsonlite)
library(bcrypt)
library(dplyr)
library(stringr)

options(encoding = "UTF-8")